"""Build clean chat.lau with correct 95-char vocab."""
import os

# Build chat.lau line by line
# Use triple-quoted strings to handle newlines cleanly
lines = [
    '--@cost(t=0)',
    '-- Load weights from JSON via HTTP',
    'varol URL="http://127.0.0.1:8080/weights.json"',
    'varol R=http.get(URL)',
    'varol J=http.jsonDecode(R.d)',
    'varol C=J.config',
    'varol W=J.weights',
    '-- Config',
    'varol V=C.vocab_size',
    'varol D=C.d_model',
    'varol H=C.n_heads',
    'varol HD=C.head_dim',
    'varol FF=C.d_ff',
    'varol CTX=C.ctx_len',
    '-- Layer offsets into W (0-indexed in Lau)',
    'varol LO0=1',
    'varol LO1=13',
    '-- Vocab: 95 printable ASCII (space to tilde)',
    'varol L=""',
    'for i=32,126 do L=L+string.char(i) end',
    '-- Verify vocab',
    'if #L~=95 then print("ERROR: vocab size is "+#L) end',
    '-- Buffers',
    'varol K0={} for i=1,CTX*D do K0[#K0+1]=0 end',
    'varol V0={} for i=1,CTX*D do V0[#V0+1]=0 end',
    'varol K1={} for i=1,CTX*D do K1[#K0+1]=0 end',
    'varol V1={} for i=1,CTX*D do V1[#V0+1]=0 end',
    'varol T={} for i=1,D*D*2 do T[#T+1]=0 end',
    'varol P=0',
    '-- Tokenize',
    'func tk(s)',
    'varol o={}',
    'for i=1,#s do',
    'varol c=string.sub(s,i,i)',
    'varol p=string.find(L,c,1,true)',
    'if p==null then p=1 end',
    'o[#o+1]=p-1',
    'end',
    'return o',
    'end',
    'func di(i) return string.sub(L,i+1,i+1) end',
    '-- Embed',
    'func er(t)',
    'varol r={}',
    'for j=1,D do r[#r+1]=W[1][t][j] end',
    'return r',
    'end',
    '-- Layer norm',
    'func ln(x,g,b)',
    'varol m=0 for j=1,D do m=m+x[j] end m=m/D',
    'varol v=0 for j=1,D do v=v+(x[j]-m)*(x[j]-m) end v=v/D',
    'varol s=1/math.sqrt(v+0.00001)',
    'for j=1,D do x[j]=(x[j]-m)*s*g[j]+b[j] end',
    'end',
    '-- Tanh approx',
    'func th(x)',
    'if x>4 then return 1 end',
    'if x<-4 then return -1 end',
    'varol a=x*x',
    'varol r=x*(1+a*(0.1333247+a*(0.0533742+a*0.0238567)))',
    'return r/(1+a*(0.3333333+a*(0.1333247+a*0.0533742)))',
    'end',
    '-- GELU',
    'func gl(x) return 0.5*x*(1+th(0.7978845608*(x+0.044715*x*x*x))) end',
    '-- Attention + MLP',
    'func attn(x,LOff,K,V)',
    'ln(x,W[LOff],W[LOff+1])',
    'for i=1,D do',
    'varol qq=0 for j=1,D do qq=qq+x[j]*W[LOff+2][i][j] end',
    'varol kk=0 for j=1,D do kk=kk+x[j]*W[LOff+3][i][j] end',
    'varol vv=0 for j=1,D do vv=vv+x[j]*W[LOff+4][i][j] end',
    'T[i]=qq T[D+i]=kk T[D*2+i]=vv',
    'end',
    'for i=1,D do K[(P-1)*D+i]=T[D+i] V[(P-1)*D+i]=T[D*2+i] end',
    'for hh=1,H do',
    'varol hs=(hh-1)*HD',
    'varol sc={}',
    'for i=1,P do',
    'varol ss=0 for d=1,HD do',
    'varol kk=(i-1)*D+hs+d',
    'varol vv=(P-1)*D+hs+d',
    'ss=ss+T[D*2+hs+d]*K[kk]',
    'end sc[#sc+1]=ss*0.5/math.sqrt(HD) end',
    'end',
    'varol mx=-999999 for i=1,P do if sc[i]>mx then mx=sc[i] end end',
    'varol sm=0 for i=1,P do sc[i]=math.exp(sc[i]-mx) sm=sm+sc[i] end',
    'for i=1,P do sc[i]=sc[i]/sm end',
    'for d=1,HD do',
    'varol ss=0 for i=1,P do',
    'varol vv=(i-1)*D+hs+d',
    'ss=ss+sc[i]*V[vv]',
    'end T[D+hs+d]=ss end',
    'end',
    'varol xr={} for i=1,D do xr[i]=x[i] end',
    'for i=1,D do',
    'varol ss=0 for j=1,D do ss=ss+T[D+j]*W[LOff+5][i][j] end',
    'x[i]=xr[i]+ss',
    'end',
    'ln(x,W[LOff+6],W[LOff+7])',
    'for i=1,D do',
    'varol ss=0 for j=1,D do ss=ss+x[j]*W[LOff+8][i][j] end',
    'T[D+i]=gl(ss+W[LOff+9][i])',
    'end',
    'for i=1,D do',
    'varol ss=0 for j=1,FF do ss=ss+T[D+j]*W[LOff+10][i][j] end',
    'x[i]=x[i]+ss+W[LOff+11][i]',
    'end',
    'end',
    'func fwd(x)',
    'if P>=CTX then',
    'for i=1,CTX-1 do for j=1,D do',
    'K0[(i-1)*D+j]=K0[i*D+j] V0[(i-1)*D+j]=V0[i*D+j]',
    'K1[(i-1)*D+j]=K1[i*D+j] V1[(i-1)*D+j]=V1[i*D+j]',
    'end end P=CTX-1 end',
    'P=P+1',
    'attn(x,LO0,K0,V0)',
    'attn(x,LO1,K1,V1)',
    'ln(x,W[26],W[27])',
    'varol lg={}',
    'for i=1,V do',
    'varol ss=0 for j=1,D do ss=ss+W[1][i][j]*x[j] end lg[#lg+1]=ss end',
    'return lg',
    'end',
    'func am(a)',
    'varol b=-999999 varol bi=1',
    'for i=1,#a do if a[i]>b then b=a[i] bi=i end end',
    'return bi',
    'end',
    'func gen(p,n)',
    'varol ts=tk(p)',
    'if #ts>CTX then',
    'varol nt={}',
    'for i=#ts-CTX+1,#ts do nt[#nt+1]=ts[i] end ts=nt end',
    'for i=1,#ts do varol x=er(ts[i]) fwd(x) end',
    'varol o="" varol li=ts[#ts]',
    'for i=1,n do',
    'varol x=er(li)',
    'varol lg=fwd(x)',
    'varol bi=am(lg)',
    'o=o+di(bi)',
    'if bi==0 then break end',
    'li=bi',
    'end return o',
    'end',
]

# Add prompts with ACTUAL newlines (use Python \n in the string)
lines.append('print("Q: Hello")')
lines.append('print("A: " + gen("Human: Hello' + '\n' + 'Bot:",30))')
lines.append('print("Q: What\'\'s 1+1?")')
lines.append('print("A: " + gen("Human: What\'\'s 1+1?' + '\n' + 'Bot:",30))')
lines.append('print("Q: What\'\'s the capital of France?")')
lines.append('print("A: " + gen("Human: What\'\'s the capital of France?' + '\n' + 'Bot:",30))')

chat_src = '\n'.join(lines)
with open('chat.lau', 'w') as f:
    f.write(chat_src)

print(f"Written chat.lau with {len(lines)} lines")
# Verify
with open('chat.lau', 'r') as f:
    content = f.read()
print(f"File size: {len(content)} bytes")
# Count actual newlines in prompts
for i, line in enumerate(content.split('\n')):
    if 'gen(' in line:
        print(f"Line {i}: {repr(line[:80])}")
